name: Simple Deploy to Host1

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download the external file
        run: curl -o mix.txt "https://raw.githubusercontent.com/tvccccc/TVCCCC/refs/heads/main/subscriptions/xray/base64/mix"

      - name: Upload to FTP Host
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          state-name: .ftp-deploy-state-mix.json
      
      - name: Keep workflow active by committing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "✅ Successful deploy on $(date)"
          git push
